use backend;
insert into users (id, first_name, last_name) values (1001, 'Farah', 'Adamo');
insert into users (id, first_name, last_name) values (1002, 'Nelly', 'Kilbourn');
insert into users (id, first_name, last_name) values (1003, 'Mikol', 'Haydney');
insert into users (id, first_name, last_name) values (1004, 'Sherwin', 'Petren');
insert into users (id, first_name, last_name) values (1005, 'Eveleen', 'Capinetti');
insert into users (id, first_name, last_name) values (1006, 'Myron', 'Padbury');
insert into users (id, first_name, last_name) values (1007, 'Haley', 'Lowndesbrough');
insert into users (id, first_name, last_name) values (1008, 'Anissa', 'Rehm');
insert into users (id, first_name, last_name) values (1009, 'Evelyn', 'Bickersteth');
insert into users (id, first_name, last_name) values (1010, 'Mack', 'Kersey');
insert into users (id, first_name, last_name) values (1011, 'Tad', 'Riep');
insert into users (id, first_name, last_name) values (1012, 'Shannan', 'Stone');
insert into users (id, first_name, last_name) values (1013, 'Cherin', 'Stone');
insert into users (id, first_name, last_name) values (1014, 'Kaiser', 'Stone');
insert into users (id, first_name, last_name) values (1015, 'Urban', 'Dugue');
insert into users (id, first_name, last_name) values (1016, 'Ameline', 'Eggleson');
insert into users (id, first_name, last_name) values (1017, 'Leesa', 'Handscombe');
insert into users (id, first_name, last_name) values (1018, 'Rolland', 'Cowpe');
insert into users (id, first_name, last_name) values (1019, 'Alexio', 'Hartfleet');
insert into users (id, first_name, last_name) values (1020, 'Adriane', 'Sutcliff');
insert into users (id, first_name, last_name) values (1021, 'Vivia', 'Richin');
insert into users (id, first_name, last_name) values (1022, 'Quill', 'Saffle');
insert into users (id, first_name, last_name) values (1023, 'Florencia', 'Bande');
insert into users (id, first_name, last_name) values (1024, 'Lorry', 'Ibbotson');
insert into users (id, first_name, last_name) values (1025, 'Marlie', 'Sambells');
insert into users (id, first_name, last_name) values (1026, 'Greg', 'Bexley');
insert into users (id, first_name, last_name) values (1027, 'Maybelle', 'Marshman');
insert into users (id, first_name, last_name) values (1028, 'Pieter', 'Andres');
insert into users (id, first_name, last_name) values (1029, 'Georgena', 'Membry');
insert into users (id, first_name, last_name) values (1030, 'Clint', 'Matiewe');
insert into users (id, first_name, last_name) values (1031, 'Wadsworth', 'McIlwain');
insert into users (id, first_name, last_name) values (1032, 'Nanette', 'Fullilove');
insert into users (id, first_name, last_name) values (1033, 'Kerk', 'Vidler');
insert into users (id, first_name, last_name) values (1034, 'Brucie', 'Tevelov');
insert into users (id, first_name, last_name) values (1035, 'Rosella', 'Kenealy');
insert into users (id, first_name, last_name) values (1036, 'Marcos', 'Oguz');
insert into users (id, first_name, last_name) values (1037, 'Uta', 'Batte');
insert into users (id, first_name, last_name) values (1038, 'Miguela', 'Devil');
insert into users (id, first_name, last_name) values (1039, 'Genvieve', 'Boatswain');
insert into users (id, first_name, last_name) values (1040, 'Ker', 'McKinless');
insert into users (id, first_name, last_name) values (1041, 'Illa', 'Dwire');
insert into users (id, first_name, last_name) values (1042, 'Mordy', 'Ranshaw');
insert into users (id, first_name, last_name) values (1043, 'Tommi', 'Blew');
insert into users (id, first_name, last_name) values (1044, 'Fredrika', 'Hailston');
insert into users (id, first_name, last_name) values (1045, 'Kaitlin', 'Armsden');
insert into users (id, first_name, last_name) values (1046, 'Dalis', 'Borman');
insert into users (id, first_name, last_name) values (1047, 'Courtnay', 'Roger');
insert into users (id, first_name, last_name) values (1048, 'Rey', 'Lukehurst');
insert into users (id, first_name, last_name) values (1049, 'Constantine', 'Andreev');
insert into users (id, first_name, last_name) values (1050, 'Crissie', 'Shyre');
insert into users (id, first_name, last_name) values (1051, 'Jimmy', 'Gaitley');
insert into users (id, first_name, last_name) values (1052, 'Itch', 'Brimmicombe');
insert into accounts (id, email, password, role) values (1001, 'admin@domain.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 1);
insert into accounts (id, email, password, role) values (1002, 'ebrunesco1@examiner.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 1);
insert into accounts (id, email, password, role) values (1003, 'teacher@domain.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1004, 'smcquaid3@alexa.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1005, 'araistrick4@ihg.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1006, 'lrowlson5@baidu.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1007, 'gpedlar6@fema.gov', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1008, 'ggarfield7@cam.ac.uk', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1009, 'hopy8@tinypic.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1010, 'ldillway9@dmoz.org', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1011, 'rholwortha@symantec.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1012, 'tlampartb@ow.ly', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1013, 'amarcosc@meetup.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1014, 'iolcotd@technorati.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1015, 'bstatherse@wunderground.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1016, 'vhatliffef@reference.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1017, 'kbraneyg@dagondesign.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1018, 'cshimmansh@yale.edu', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1019, 'nkroli@boston.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1020, 'bhetterichj@google.ca', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1021, 'hkellingk@phpbb.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1022, 'mgolderl@tinyurl.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1023, 'bvernym@bbb.org', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1024, 'jjuppn@plala.or.jp', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1025, 'ccasemento@comsenz.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1026, 'htomaszynskip@netvibes.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1027, 'ccettellq@businessweek.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1028, 'wbootr@cbsnews.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1029, 'hbooths@oracle.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1030, 'smarquesst@hugedomains.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1031, 'nlenihanu@hc360.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1032, 'sbrosiv@columbia.edu', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1033, 'dkirganw@blogs.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1034, 'hrustonx@paypal.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1035, 'hpassyy@amazonaws.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1036, 'ggommz@statcounter.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1037, 'dduhamel10@drupal.org', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1038, 'bmalkin11@webs.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1039, 'bcouth12@tinypic.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1040, 'gmulvagh13@army.mil', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1041, 'bodonohue14@nbcnews.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1042, 'srobottom15@harvard.edu', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1043, 'tmacronald16@vkontakte.ru', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1044, 'mtitterton17@unc.edu', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1045, 'kwintersgill18@irs.gov', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1046, 'ajenks19@mail.ru', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1047, 'cdaley1a@bbc.co.uk', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1048, 'edecleyne1b@exblog.jp', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1049, 'ljacqueme1c@dmoz.org', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1050, 'bwonter1d@elegantthemes.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1051, 'leakens1e@skype.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
insert into accounts (id, email, password, role) values (1052, 'gmcmenemy1f@nydailynews.com', '$2a$10$hIezejwR6XUeLojyIsuVy.CzNsyo.YJFJFBTVHcpmcB3wVS0dBqzu', 2);
