use backend;


insert into student_groups (id, course, description) values (1, 5, 'Research and Development');
insert into student_groups (id, course, description) values (2, 3, 'Services');
insert into student_groups (id, course, description) values (3, 4, 'Research and Development');
insert into student_groups (id, course, description) values (4, 4, 'Services');
insert into student_groups (id, course, description) values (5, 3, 'Accounting');
insert into student_groups (id, course, description) values (6, 3, 'Research and Development');
insert into student_groups (id, course, description) values (7, 4, 'Sales');
insert into student_groups (id, course, description) values (8, 2, 'Engineering');
insert into student_groups (id, course, description) values (9, 2, 'Business Development');
insert into student_groups (id, course, description) values (10, 2, 'Sales');
insert into student_groups (id, course, description) values (11, 1, 'Engineering');
insert into student_groups (id, course, description) values (12, 3, 'Training');
insert into student_groups (id, course, description) values (13, 3, 'Marketing');
insert into student_groups (id, course, description) values (14, 3, 'Sales');
insert into student_groups (id, course, description) values (15, 4, 'Research and Development');
insert into student_groups (id, course, description) values (16, 4, 'Business Development');
insert into student_groups (id, course, description) values (17, 2, 'Support');
insert into student_groups (id, course, description) values (18, 3, 'Legal');
insert into student_groups (id, course, description) values (19, 3, 'Accounting');
insert into student_groups (id, course, description) values (20, 2, 'Support');
insert into student_groups (id, course, description) values (21, 4, 'Services');
insert into student_groups (id, course, description) values (22, 4, 'Product Management');
insert into student_groups (id, course, description) values (23, 2, 'Training');
insert into student_groups (id, course, description) values (24, 1, 'Legal');
insert into student_groups (id, course, description) values (25, 1, 'Product Management');
insert into student_groups (id, course, description) values (26, 2, 'Business Development');
insert into student_groups (id, course, description) values (27, 5, 'Training');
insert into student_groups (id, course, description) values (28, 1, 'Research and Development');
insert into student_groups (id, course, description) values (29, 5, 'Engineering');
insert into student_groups (id, course, description) values (30, 5, 'Services');
insert into student_groups (id, course, description) values (31, 1, 'Support');
insert into student_groups (id, course, description) values (32, 5, 'Human Resources');
insert into student_groups (id, course, description) values (33, 5, 'Business Development');
insert into student_groups (id, course, description) values (34, 1, 'Research and Development');
insert into student_groups (id, course, description) values (35, 2, 'Support');
insert into student_groups (id, course, description) values (36, 3, 'Accounting');
insert into student_groups (id, course, description) values (37, 3, 'Marketing');
insert into student_groups (id, course, description) values (38, 3, 'Research and Development');
insert into student_groups (id, course, description) values (39, 4, 'Sales');
insert into student_groups (id, course, description) values (40, 2, 'Marketing');
insert into student_groups (id, course, description) values (41, 5, 'Legal');
insert into student_groups (id, course, description) values (42, 2, 'Product Management');
insert into student_groups (id, course, description) values (43, 3, 'Training');
insert into student_groups (id, course, description) values (44, 4, 'Training');
insert into student_groups (id, course, description) values (45, 3, 'Legal');
insert into student_groups (id, course, description) values (46, 1, 'Research and Development');
insert into student_groups (id, course, description) values (47, 1, 'Engineering');
insert into student_groups (id, course, description) values (48, 2, 'Training');
insert into student_groups (id, course, description) values (49, 3, 'Training');
insert into student_groups (id, course, description) values (50, 1, 'Engineering');
insert into student_groups (id, course, description) values (51, 4, 'Sales');
insert into student_groups (id, course, description) values (52, 4, 'Sales');
insert into student_groups (id, course, description) values (53, 2, 'Training');
insert into student_groups (id, course, description) values (54, 5, 'Sales');
insert into student_groups (id, course, description) values (55, 1, 'Product Management');
insert into student_groups (id, course, description) values (56, 4, 'Legal');
insert into student_groups (id, course, description) values (57, 2, 'Accounting');
insert into student_groups (id, course, description) values (58, 1, 'Human Resources');
insert into student_groups (id, course, description) values (59, 2, 'Legal');
insert into student_groups (id, course, description) values (60, 3, 'Research and Development');
insert into student_groups (id, course, description) values (61, 3, 'Support');
insert into student_groups (id, course, description) values (62, 4, 'Engineering');
insert into student_groups (id, course, description) values (63, 2, 'Services');
insert into student_groups (id, course, description) values (64, 2, 'Legal');
insert into student_groups (id, course, description) values (65, 3, 'Support');
insert into student_groups (id, course, description) values (66, 4, 'Marketing');
insert into student_groups (id, course, description) values (67, 5, 'Business Development');
insert into student_groups (id, course, description) values (68, 4, 'Services');
insert into student_groups (id, course, description) values (69, 1, 'Training');
insert into student_groups (id, course, description) values (70, 3, 'Marketing');
insert into student_groups (id, course, description) values (71, 5, 'Legal');
insert into student_groups (id, course, description) values (72, 3, 'Training');
insert into student_groups (id, course, description) values (73, 5, 'Sales');
insert into student_groups (id, course, description) values (74, 5, 'Product Management');
insert into student_groups (id, course, description) values (75, 1, 'Marketing');
insert into student_groups (id, course, description) values (76, 2, 'Engineering');
insert into student_groups (id, course, description) values (77, 2, 'Business Development');
insert into student_groups (id, course, description) values (78, 2, 'Support');
insert into student_groups (id, course, description) values (79, 4, 'Services');
insert into student_groups (id, course, description) values (80, 1, 'Accounting');
insert into student_groups (id, course, description) values (81, 3, 'Product Management');
insert into student_groups (id, course, description) values (82, 2, 'Human Resources');
insert into student_groups (id, course, description) values (83, 3, 'Services');
insert into student_groups (id, course, description) values (84, 2, 'Business Development');
insert into student_groups (id, course, description) values (85, 4, 'Business Development');
insert into student_groups (id, course, description) values (86, 2, 'Support');
insert into student_groups (id, course, description) values (87, 5, 'Business Development');
insert into student_groups (id, course, description) values (88, 2, 'Accounting');
insert into student_groups (id, course, description) values (89, 1, 'Support');
insert into student_groups (id, course, description) values (90, 1, 'Services');
insert into student_groups (id, course, description) values (91, 4, 'Accounting');
insert into student_groups (id, course, description) values (92, 2, 'Legal');
insert into student_groups (id, course, description) values (93, 4, 'Human Resources');
insert into student_groups (id, course, description) values (94, 2, 'Sales');
insert into student_groups (id, course, description) values (95, 2, 'Sales');
insert into student_groups (id, course, description) values (96, 1, 'Support');
insert into student_groups (id, course, description) values (97, 1, 'Product Management');
insert into student_groups (id, course, description) values (98, 5, 'Training');
insert into student_groups (id, course, description) values (99, 1, 'Marketing');
insert into student_groups (id, course, description) values (100, 4, 'Support');
